kafka:
  replicaCount: 5
  global:
    storageClass: "ssd"
  heapOpts: -Xms4096m -Xmx4096m
  logRetentionBytes: _303741824002
  maxMessageBytes: _10485760
  socketRequestMaxBytes: _104857600
  defaultReplicationFactor: 2
  numPartitions: 3

kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: debezium
          bootstrapServers: kafka:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false