kafka:
  replicaCount: 30
  global:
    storageClass: "ssd"
  heapOpts: -Xms4096m -Xmx4096m
#  logRetentionBytes: _30374182400
  maxMessageBytes: _10485760
  socketRequestMaxBytes: _104857600
  defaultReplicationFactor: 3
  offsetsTopicReplicationFactor: 3
  transactionStateLogReplicationFactor: 3
  provisioning:
    replicationFactor: 3
  numPartitions: 2
  persistence:
    size: 500Gi

kafka-ui:
  service:
    type: LoadBalancer
    port: 8080
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: debezium
          bootstrapServers: kafka:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false