apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debezium-data-sync
spec:
  minAvailable: 2  # 网页未直接提及，但符合K8s官方标准
  selector:
    matchLabels:
      app: debezium-data-sync  # 匹配Deployment标签